---
title: "R Notebook"
output: html_notebook
---

```{r}
library(mlr3)           # For the basics
library(mlr3learners)   # For k-nn learner
library(palmerpenguins) # For penguins

# Creating a task from our penguin data
penguin_task <- TaskClassif$new(
  id = "penguins", 
  backend = penguins, 
  target = "species"
)

# Contains our penguin dataset
penguin_task$data()

# Display feature and target variable assignment
penguin_task$col_roles[c("feature", "target")]

# Maybe not all variables are useful for this task
penguin_task$set_col_roles(cols = c("island", "sex", "year"), remove_from = "feature")
penguin_task$col_roles[c("feature", "target")]

# Some variables have missing values
penguin_task$missings()


# penguin_task <- tsk("penguins")
```

```{r}
# Lots of learners to choose from
mlr_learners

# But we only want classifiers for now
mlr_learners$keys(pattern = "classif")

# More specifically, the knn one
mlr_learners$get("classif.kknn")

# We can also access it more quickly with lrn()
knn_learner <- lrn("classif.kknn")

knn_learner$help()

# What parameters does this learner have?
knn_learner$param_set
```

### Train- and test-split

```{r}
penguin_train_set = sample(penguin_task$nrow, 0.8 * penguin_task$nrow)
penguin_test_set = setdiff(seq_len(penguin_task$nrow), train_set)
```

```{r}
knn_learner$train(penguin_task, row_ids = penguin_train_set)

knn_learner$model
```

```{r}
penguins_prediction = knn_learner$predict(penguin_task, row_ids = penguin_test_set)
penguins_prediction
```

```{r}

```

