---
title: "02: Growing Trees"
date: "`r Sys.time()`"
output: 
  html_notebook: 
    toc: yes
    theme: flatly
    number_sections: yes
---

```{r setup}
library(mlr3)           # For the basics
library(mlr3learners)   # For k-nn learner
library(palmerpenguins) # For penguins
library(mlr3viz)        # For plotting
library(ggplot2)        # For plotting

# remove NAs for simplicity in this example
# (handling missing data is a can of worms for another time :)
penguins <- na.omit(penguins)
```

# Task Setup

```{r penguins-task-creation}
# Creating a classification task from our penguin data
penguin_task <- TaskClassif$new(
  id = "penguins", 
  backend = penguins, 
  target = "species"
)

# Display feature and target variable assignment
penguin_task$col_roles[c("feature", "target")]

# This time we're only dropping the year column
penguin_task$set_col_roles(cols = c("year"), remove_from = "feature")

penguin_task$col_roles[c("feature", "target")]

# Train/test split
set.seed(26)
penguin_train_set <- sample(penguin_task$nrow, 0.8 * penguin_task$nrow)
penguin_test_set <- setdiff(seq_len(penguin_task$nrow), penguin_train_set)
```

# Learner: Single Tree

```{r}
learner_tree <- lrn("classif.rpart")
learner_forest <- lrn("classif.ranger")
```

